2025-07-27 20:20:32,004 INFO: Base de datos PostgreSQL inicializada correctamente [in C:\Users\erick\OneDrive\Desktop\Miligan-Tennis\app.py:135]
2025-07-27 20:20:32,458 INFO: Base de datos PostgreSQL inicializada correctamente [in C:\Users\erick\OneDrive\Desktop\Miligan-Tennis\app.py:135]
2025-07-28 02:35:51,821 INFO: Base de datos PostgreSQL inicializada correctamente [in C:\Users\erick\OneDrive\Desktop\Miligan-Tennis\app.py:135]
2025-07-28 02:36:09,923 INFO: Base de datos PostgreSQL inicializada correctamente [in C:\Users\erick\OneDrive\Desktop\Miligan-Tennis\app.py:135]
2025-07-28 02:36:10,335 INFO: Base de datos PostgreSQL inicializada correctamente [in C:\Users\erick\OneDrive\Desktop\Miligan-Tennis\app.py:135]
2025-07-28 03:25:08,568 INFO: Base de datos PostgreSQL inicializada correctamente [in C:\Users\erick\OneDrive\Desktop\Miligan-Tennis\app.py:135]
2025-07-28 03:37:13,050 ERROR: Unhandled Exception: 429 Too Many Requests: 1000 per 1 hour [in C:\Users\erick\OneDrive\Desktop\Miligan-Tennis\app.py:39]
Traceback (most recent call last):
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 868, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1243, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1172, in _check_request_limit
    raise e
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1169, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1153, in __evaluate_limits
    raise RateLimitExceeded(
    ...<2 lines>...
    )
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 1000 per 1 hour
2025-07-28 03:37:13,134 ERROR: Unhandled Exception: 429 Too Many Requests: 1000 per 1 hour [in C:\Users\erick\OneDrive\Desktop\Miligan-Tennis\app.py:39]
Traceback (most recent call last):
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 868, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1243, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1172, in _check_request_limit
    raise e
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1169, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1153, in __evaluate_limits
    raise RateLimitExceeded(
    ...<2 lines>...
    )
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 1000 per 1 hour
2025-07-28 03:37:13,349 ERROR: Unhandled Exception: 429 Too Many Requests: 1000 per 1 hour [in C:\Users\erick\OneDrive\Desktop\Miligan-Tennis\app.py:39]
Traceback (most recent call last):
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 868, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1243, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1172, in _check_request_limit
    raise e
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1169, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1153, in __evaluate_limits
    raise RateLimitExceeded(
    ...<2 lines>...
    )
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 1000 per 1 hour
2025-07-28 03:37:13,456 ERROR: Unhandled Exception: 429 Too Many Requests: 1000 per 1 hour [in C:\Users\erick\OneDrive\Desktop\Miligan-Tennis\app.py:39]
Traceback (most recent call last):
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 868, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1243, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1172, in _check_request_limit
    raise e
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1169, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1153, in __evaluate_limits
    raise RateLimitExceeded(
    ...<2 lines>...
    )
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 1000 per 1 hour
2025-07-28 03:37:13,534 ERROR: Unhandled Exception: 429 Too Many Requests: 1000 per 1 hour [in C:\Users\erick\OneDrive\Desktop\Miligan-Tennis\app.py:39]
Traceback (most recent call last):
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 868, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1243, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1172, in _check_request_limit
    raise e
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1169, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1153, in __evaluate_limits
    raise RateLimitExceeded(
    ...<2 lines>...
    )
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 1000 per 1 hour
2025-07-28 03:37:13,658 ERROR: Unhandled Exception: 429 Too Many Requests: 1000 per 1 hour [in C:\Users\erick\OneDrive\Desktop\Miligan-Tennis\app.py:39]
Traceback (most recent call last):
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 868, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1243, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1172, in _check_request_limit
    raise e
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1169, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1153, in __evaluate_limits
    raise RateLimitExceeded(
    ...<2 lines>...
    )
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 1000 per 1 hour
2025-07-28 03:37:13,659 ERROR: Unhandled Exception: 429 Too Many Requests: 1000 per 1 hour [in C:\Users\erick\OneDrive\Desktop\Miligan-Tennis\app.py:39]
Traceback (most recent call last):
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 868, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1243, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1172, in _check_request_limit
    raise e
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1169, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erick\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_limiter\extension.py", line 1153, in __evaluate_limits
    raise RateLimitExceeded(
    ...<2 lines>...
    )
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 1000 per 1 hour
2025-07-28 04:02:32,397 INFO: Base de datos PostgreSQL inicializada correctamente [in C:\Users\erick\OneDrive\Desktop\Miligan-Tennis\app.py:140]
